version: "3.8"
services:
    db:
      container_name: db
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - 5432:5432

    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: app
      environment:
        - PORT=${PORT}
      ports:
        - '3000:3000'
      depends_on:
        - db
      volumes:
        - ./src:/app/src
